
USE ContosoRetailDW

/*USANDO ALGUMAS FUNÇÕES BASICAS DO SQL*/

DECLARE @USER VARCHAR(30)
SET @USER = ' Maria Maria '


SELECT 
	@USER AS NAME,
	LEN(@USER) AS TAMANHO,    --FUNÇÃO DE CONTAR OS CARACTERES, ELE APENAS CONTA COM OS ESPAÇOS DA ESQUERDA
	LTRIM(@USER) AS ESQUERDA,  
	RTRIM(@USER) AS DIREITA,
	TRIM(@USER) AS TODOS,   -- REMOVER ESPAÇOS
	UPPER(@USER) AS MAIUSCULOS,           --DEIXAR TUDO MAUSCULOS
	UPPER(TRIM(@USER)) AS MAIUSCULOS_SEM_ESPACOS,                   -- JUNTANDO DUAS FUNÇÕES
	LOWER(TRIM(@USER)) AS MINUSCULOS_SEM_ESPACOS      --DEIXAR TUDO MINUSCULOS