



-- USAR UMA CONSULTA PARA FAZER UMA OUTRA CONSULTA

USE ContosoRetailDW

SELECT
	AVG(UnitPrice) AS MEDIA
FROM DimProduct

-- USANDO UM SELECT PARA PEGAR UM RESULTADO PARA DENTRO DE UMA CONSULTA
SELECT
	ProductKey,
	UnitPrice
FROM DimProduct
WHERE UnitPrice <= (SELECT AVG(UnitPrice) AS MEDIA FROM DimProduct) -- SUB CONSULTA
ORDER BY UnitPrice DESC