
-- SEMPRE CHAMAR O BANCO EM QUE VAI SER CRIADO AS TABELAS OU MANIPULÇÕES DE DADOS

USE PRIMEIRO_BD

-- CRIANDO UMA TABELA E INSERINDO OS TIPOS DE DADOS

CREATE TABLE CLIENTE
(
	ID_CLIENTE INT, -- COLUNA TIPO INT
	NOME VARCHAR(30),-- COLUNA TIPO TEXTO (VARCHAR)
	DATA_CADASTRO DATETIME, -- COLUNA TIPO DATA
	EMAIL VARCHAR(30) -- COLUNA TIPO TEXTO (VARCHAR)
)
