

USE PRIMEIRO_BD -- USANDO DADOS DOS BANCO (CHAMANDO ELE)

-- DELETANDO DADOS DE UMA TABELA
-- SEMPRE USAR WHERE PARA COLOCAR AS CONDIÇÕES NA TABELA

DELETE CLIENTE
WHERE						-- CONDIÇÃO "ONDE"
	ID_CLIENTE = 1

SELECT * FROM CLIENTE

