

USE PRIMEIRO_BD

--ALTERARANDO OS DADOS DA COLUNA ESPECIFICA

UPDATE CLIENTE
SET EMAIL = 'CONTATO1111_@MATEUS.COM.BR'
WHERE ID_CLIENTE = 1  -- O WHERE DEFINE UMA CONDICAO PARA PODER INSERIR APENAS ONDE QUERO (ONDE)


-- ATUALIZZANDO MAIS DE UMA COLUNA

UPDATE CLIENTE
SET
	EMAIL = 'TESTE1',
	NOME = 'TESTE 2'
WHERE
	ID_CLIENTE = 3


SELECT * FROM CLIENTE