

USE ContosoRetailDW

-- DIFERENÇA ENTRE DUAS DATAS

--DATEDIFF(intervalo, data_inicio, data_final)

SELECT 
	DATEDIFF(DAY, '2023-07-10', GETDATE()) AS DIA,
	DATEDIFF(MONTH, '2023-06-10', GETDATE()) AS MES,
	DATEDIFF(YEAR, '2002-07-10', GETDATE()) AS ANO

SELECT DISTINCT TOP 100
	S.DateKey,
	GETDATE() AS HOJE,
	DATEDIFF(DAY, S.DateKey, GETDATE()) AS DIF_DIAS
FROM FactOnlineSales AS S

ORDER BY 1 DESC

--PODE SER USADO PARA FILTRAR AS VENDAS QUE ACONTECERAM DENTRO DE TANTOS DIAS DE DIFERENÇA
