

USE ContosoRetailDW


-- ADICIONADO INTERVALOS A UMA DATA

--DATEADD(intervalo, quantidade, data)

--ADICIOANDO NUMEROS AS DATA, SOMANDO OU SUBTRAINDO
SELECT
	GETDATE() AS HOJE,
	DATEADD(DAY, 10, GETDATE()) AS DIA,
	DATEADD(MONTH, 1, GETDATE()) AS UM_MES,
	DATEADD(MONTH, -1, GETDATE()) AS MENOS_UM_MES,
	DATEADD(YEAR, 1, GETDATE()) AS UM_ANO