

USE ContosoRetailDW


--END OF MONTH

SELECT EOMONTH(GETDATE())


--DICIONADO MESES
SELECT
	GETDATE(),
	EOMONTH(GETDATE()) AS FINAL_DO_ATUAL,
	EOMONTH(GETDATE(), 1) AS FINAL_MES_SEGUINTE,
	EOMONTH(GETDATE(), -1) AS FINAL_MES_PASSADO