

USE ContosoRetailDW

-- FUNÇAO PARA TER A HORA E DATA ATUAL

SELECT
	GETDATE() AS DATA_ATUAL

-- SOMANDO DIAS
SELECT
	GETDATE() +10 AS DATA_ATUAL_10

--SELECIONANDO O ANO
SELECT
	YEAR(GETDATE()) AS ANO

--SELECIONANDO O MES
SELECT
	MONTH(GETDATE()) AS MES

--SELECIONANDO O DIA
SELECT
	DAY(GETDATE()) AS DIA

-- FILTRANDO DADOS USANDO APENAS AS DATAS QUE QUEREMOS
SELECT
	*
FROM FactOnlineSales
WHERE YEAR(DateKey) = 2007
AND MONTH(DateKey) = 12
AND DAY(DateKey) = 31
ORDER BY Datekey DESC