

USE ContosoRetailDW

/*CONCATENAR TEXTOS USANDO + OU CONCAT*/

DECLARE @USER VARCHAR(30)
SET @USER = ' Maria Maria '

DECLARE @USER2 VARCHAR(30)
SET @USER2 = ' Joao Joao '

SELECT 
	@USER + @USER2 AS NAMES

--USANDO CONCAT
SELECT CONCAT('MATEUS ', @USER2, 'CUCKER', @USER)