
USE ContosoRetailDW

-- GUARDAR INFORMAÇÕES EM UM ESPAÇO
-- TEM QUE INFORMAR O TIPO DE DADOS DA VARIAVEL
-- TEM QUE USAR O @ NA FRENTE

DECLARE @USUARIO VARCHAR(30)
SET @USUARIO = ' ROBERTO CARLOS '

SELECT @USUARIO AS NAME

--PODEMOS USAR PARA FILTROS OU PARAMENTROS DE CONSULTAS



USE ContosoRetailDW

-- DEFININDO VARIAVEL
DECLARE @PROD INT 
--COLOCANDO INFORMAÇÃO NELA
SET @PROD = 782

--FILTRANDO DADOS USADO ELA
SELECT TOP 100 * FROM FactOnlineSales
WHERE ProductKey = @PROD


