
USE Chinook

SELECT 
       [TrackId]
      ,[Name]
      ,[AlbumId]
      ,[Milliseconds]
      ,[UnitPrice]
      ,ROW_NUMBER() OVER(ORDER BY Unitprice ASC) AS 'ROW_NUMBER' -- POSIÇÕES POR Unitprice
      ,RANK() OVER(ORDER BY Unitprice ASC) AS 'RANK' --DEIXNADO AS POSIÇÕES QUE SÃO IGUAIS COM O MESMO INDICE MAS PULA QUANDO TROCA A LINHA 
      ,DENSE_RANK() OVER(ORDER BY Unitprice ASC) AS 'DENSE_RANK' --DEIXNADO AS POSIÇÕES QUE SÃO IGUAIS COM O MESMO INDICE MAS CONTINUA QUANDO TROCA A LINHA 
      ,NTILE(12) OVER(ORDER BY UnitPrice ASC) AS 'NTILE' -- DIVIDINDO A TABELA EM GRUPOS, PELA CRITERIO QUE EU QUISER!
  FROM [Chinook].[dbo].[Track]




  SELECT 
       [TrackId]
      ,[Name]
      ,[AlbumId]
      ,[Milliseconds]
      ,[GenreId]
      ,[UnitPrice]
      ,ROW_NUMBER() OVER(ORDER BY Unitprice ASC) AS 'ROW_NUMBER' -- POSIÇÕES POR Unitprice
      ,RANK() OVER(ORDER BY Unitprice ASC) AS 'RANK' --DEIXNADO AS POSIÇÕES QUE SÃO IGUAIS COM O MESMO INDICE MAS PULA QUANDO TROCA A LINHA 
      ,DENSE_RANK() OVER(ORDER BY Unitprice ASC) AS 'DENSE_RANK' --DEIXNADO AS POSIÇÕES QUE SÃO IGUAIS COM O MESMO INDICE MAS CONTINUA QUANDO TROCA A LINHA 
      ,NTILE(12) OVER(PARTITION BY GenreId ORDER BY UnitPrice ASC) AS 'NTILE' -- DIVIDINDO A TABELA EM GRUPOS, PELA CRITERIO QUE EU QUISER!
  FROM [Chinook].[dbo].[Track]

 

 
